/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32411xx.h"

#define USER_BUTTON_HIGH LOW
#define USER_BUTTON_LOW  HIGH

void driveLedWithButton(void);

int main(void)
{
	driveLedWithButton();

	return 0;
}

void driveLedWithButton(void) {
	GPIO_Config_t button = {
			.PinNumber = GPIO_PIN_13,
			.InputMode = GPIO_MODE_INPUT,
			.PUPD = GPIO_NO_PUPD,
			.pGPIOx = GPIOC
	};

	GPIOx_init(&button);

	GPIO_Config_t led = {
			.PinNumber = GPIO_PIN_5,
			.InputMode = GPIO_MODE_OUTPUT,
			.OutputType = GPIO_OP_PUPD,
			.Speed = GPIO_SPEED_MED,
			.PUPD = GPIO_NO_PUPD,
			.pGPIOx = GPIOA
	};

	GPIOx_init(&led);

	while(1) {
		if (GPIOx_ReadInputPin(button.pGPIOx, GPIO_PIN_13) == USER_BUTTON_HIGH) {
			GPIOx_WriteOutput(led.pGPIOx, GPIO_PIN_5, HIGH);
		} else {
			GPIOx_WriteOutput(led.pGPIOx, GPIO_PIN_5, LOW);
		}
	}
}



